GET https://jira.navis.com/rest/api/latest/issue/ARGO-192811
Content-Type: application/json
Authorization: Basic amFpbm1vOk5hdmlzITEyMw==

###

GET http://localhost:8080/triage
Content-Type: application/json

###

#ISSUE API
Content-Type: application/json
GET https://jira.navis.com/rest/api/2/search?jql=project=10010&fields=key,summary,description,created,components,status,watches,issuetype,assignee&maxResults=1000&startAt=1000
Authorization: Basic amFpbm1vOk5hdmlzITEyMw==

###


#PROJECT API
GET https://jira.navis.com/rest/api/2/project/10010
Content-Type: application/json
Authorization: Basic amFpbm1vOk5hdmlzITEyMw==

###

GET https://jira.navis.com/rest/api/2/search?jql=project=10010&maxResults=0
Content-Type: application/json
Authorization: Basic amFpbm1vOk5hdmlzITEyMw==

###

